tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
brew "git"
brew "node"
brew "python"
brew "python3"
brew "stow", link: false
brew "zsh-syntax-highlighting"
cask "iterm2"
cask "steam"
cask "sublime-text"
cask "transmission"
